version: '3'

tasks:
  default:
    desc: list all tasks
    cmds:
    - task --list

  run-dev:
    desc: Run the go project with air
    cmds:
    - air

  bootstrap:
    desc: Initialize the project and install dependencies
    dir: src
    cmds:
    - go mod

  start:
    desc: Start docker compose services
    dir: src
    cmds:
    - docker compose up -d

  build:
    desc: Stop docker compose services
    dir: src
    cmds:
    - docker compose build

  down:
    desc: Stop docker compose services
    dir: src
    cmds:
    - docker compose down

  logs:
    desc: View docker compose logs
    dir: src
    cmds:
    - docker compose logs -f

  deploy:
    desc: deploy helm chart
    cmds:
    - helm upgrade --install fluxcd-viewer helm/ -n fluxcd-viewer --create-namespace --wait --timeout 1m
