root = "."
tmp_dir = "../tmp"

[build]
  cmd = "go build -o ../tmp/main ."
  bin = "../tmp/main"
  delay = 1000
  exclude_dir = ["assets", "tmp", "test", "vendor", ".git"]
  include_ext = ["go", "tpl", "tmpl", "html", "css", "js", "svg"]
  exclude_regex = ["_test.go"]
  follow_symlink = true
  kill_delay = "0.5s"